hp/account/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'account'
urlpatterns = [
    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
    url(r'^register/(?P<key>\w+)/$', views.ConfirmRegistrationView.as_view(),
        name='register_confirm'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^sessions/$', views.SessionsView.as_view(), name='sessions'),
    url(r'^notifications/$', views.NotificationsView.as_view(), name='notifications'),
    url(r'^password/$', views.SetPasswordView.as_view(), name='set_password'),
    url(r'^password/reset/$', views.ResetPasswordView.as_view(), name='reset_password'),
    url(r'^password/reset/(?P<key>\w+)/$', views.ConfirmResetPasswordView.as_view(),
        name='reset_password_confirm'),
    url(r'^email/$', views.SetEmailView.as_view(), name='set_email'),
    url(r'^email/(?P<key>\w+)/$', views.ConfirmSetEmailView.as_view(), name='set_email_confirm'),
    url(r'^uploads/$', views.HttpUploadView.as_view(), name='xep0363'),
    url(r'^gpg/$', views.GpgView.as_view(), name='gpg'),
    url(r'^gpg/(?P<pk>\d+)/$', views.ManageGpgView.as_view(), name='manage_gpg'),
    url(r'^gpg/add/$', views.AddGpgView.as_view(), name='add_gpg'),
    url(r'^log/$', views.RecentActivityView.as_view(), name='log'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^api/check-user/$', views.UserAvailableView.as_view(), name='api-check-user'),
    url(r'^api/xep0363/(?P<pk>\d+)/$', views.DeleteHttpUploadView.as_view(),
        name='api-xep0363-delete'),
    url(r'^api/sessions/(?P<resource>.+)/$$', views.StopUserSessionView.as_view(),
        name='api-stop-user-session'),
    url(r'^delete/$', views.DeleteAccountView.as_view(), name='delete'),
    url(r'^delete/(?P<key>\w+)/$', views.ConfirmDeleteAccountView.as_view(),
        name='delete_confirm'),
    url(r'^$', views.UserView.as_view(), name='detail'),
]

hp/blog/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url

from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^b/(?P<slug>[a-z0-9-_äöüß]+)/$', views.BlogPostView.as_view(), name='blogpost'),
    url(r'^p/(?P<slug>[a-z0-9-_äöüß]+)/$', views.PageView.as_view(), name='page'),
    url(r'^$', views.BlogPostListView.as_view(), name='home'),
]

hp/core/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import ugettext_lazy as _

from blog.sitemaps import BlogPostSitemap
from blog.sitemaps import PageSitemap

from . import views
from .sitemaps import StaticSitemap

sitemaps = {
    'blog': BlogPostSitemap,
    'page': PageSitemap,
    'static': StaticSitemap,
}


app_name = 'core'
urlpatterns = [
    url(_(r'^contact/$'), views.ContactView.as_view(), name='contact'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^api/set-lang/$', views.SetLanguageView.as_view(), name='api-set-lang'),
]

hp/hp/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

from core.urlpatterns import i18n_url

urlpatterns = [
    url(r'^%s/' % settings.ADMIN_URL.strip('/'), admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^account/', include('account.urls')),
    url(r'^feed/', include('feed.urls')),
    url(r'^chat/', include('conversejs.urls')),
    url(r'^xep0363/', include('xmpp_http_upload.urls', namespace='xmpp-http-upload')),
    i18n_url(r'^', include('core.urls')),
    url(r'^', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hp/core/views.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

import ipaddress
import logging

from django.conf import settings
from django.core.cache import cache
from django.db.models import Q
from django.http import Http404
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.functional import Promise
from django.utils.http import is_safe_url
from django.utils.translation import ugettext as _
from django.utils.translation import LANGUAGE_SESSION_KEY
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormView

from core.utils import canonical_link

from .constants import ACTIVITY_CONTACT
from .forms import AnonymousContactForm
from .forms import ContactForm
from .tasks import send_contact_email
from .utils import check_dnsbl

log = logging.getLogger(__name__)
_BLACKLIST = getattr(settings, 'SPAM_BLACKLIST', set())
_RATELIMIT_WHITELIST = getattr(settings, 'RATELIMIT_WHITELIST', set())
_RATELIMIT_CONFIG = getattr(settings, 'RATELIMIT_CONFIG', {})


class TranslateSlugViewMixin(object):
    """A view mixin that allows DetailView to work with translated slugs.

    .. WARNING:: This mixin assumes:

       * There is a ``slug`` kwarg in the URL config
       * The model has a translated slug field (like core.BlogPost and core.Page)
       * The model has a ``get_absolute_url()`` method.

    Background: By default, get_object() would filter for the slug field, the translated
    database field uses the current active language. So this queryset::

        >>> from blog.models import Page
        >>> Page.objects.filter(slug='foo')

    ... returns a different result depending on the browser language (on the database level,
    this would result in a ``WHERE slug_en="foo"`` in an English browser). This means that
    the URL "/page/english-slug" works in an English browser but NOT in a German browser.

    So ``get_object()`` is overwritten to filter for all language slugs. ``get()`` additionally
    returns a redirect to the slug in the current language if it's not the same as the one viewed.
    """

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        # If the slug used in the view is different from the slug in the current language, redirect
        # to the latter.
        if kwargs['slug'] != self.object.slug.current:
            return HttpResponseRedirect(self.object.get_absolute_url())

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        slug = self.kwargs.get(self.slug_url_kwarg)

        # filter for slugs in all languages
        filter = Q()
        for lang, _name in settings.LANGUAGES:
            filter |= Q(**{'slug_%s' % lang: slug})

        queryset = queryset.filter(filter)

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj


class StaticContextMixin(object):
    """Simple mixin that allows you to add a static dictionary to the template context."""

    static_context = None

    def get_context_data(self, **kwargs):
        context = super(StaticContextMixin, self).get_context_data(**kwargs)
        if self.static_context is not None:
            context.update(self.static_context)

        urlname = '%s:%s' % (self.request.resolver_match.namespace,
                             self.request.resolver_match.url_name)

        if urlname in settings.SOCIAL_MEDIA_TEXTS:
            texts = settings.SOCIAL_MEDIA_TEXTS[urlname]

            for key, value in texts.items():
                if isinstance(value, (str, Promise)):
                    value = value % self.request.site
                context[key] = value

        # set default canonical URL
        context.setdefault('canonical_url', canonical_link(self.request.path))

        return context


class AntiSpamMixin(object):
    blacklist_template = 'core/antispam/blacklist.html'
    dnsbl_template = 'core/antispam/dnsbl.html'
    rate_template = 'core/antispam/rate.html'
    rate_activity = None

    def get_rate_cache_key(self, request):
        return 'rate_%s_%s' % (self.rate_activity, request.META['REMOTE_ADDR'])

    def check_rate(self, request, rate_addr):
        """Check if the given IP is currently ratelimited for this view.

        Returns
        -------

        bool
            Returns ``False`` if the IP is currently ratelimited for this activity, ``True``
            otherwise.
        """

        if self.rate_activity is None:
            return True
        if rate_addr in _RATELIMIT_WHITELIST or settings.DEBUG is True:
            return True

        cache_key = self.get_rate_cache_key(request)
        now = timezone.now()
        timestamps = cache.get(cache_key) or []
        config = _RATELIMIT_CONFIG.get(self.rate_activity, {})

        for delta, ratelimit in config:
            offset = now - delta
            if len([t for t in timestamps if t >= offset]) > ratelimit:
                return False
        return True

    def ratelimit(self, request):
        if settings.DEBUG is True:
            rate_addr = request.GET.get('ratelimit', request.META['REMOTE_ADDR'])
        else:
            rate_addr = request.META['REMOTE_ADDR']

        if rate_addr in _RATELIMIT_WHITELIST or self.rate_activity is None:
            return

        cache_key = self.get_rate_cache_key(request)
        timestamps = cache.get(cache_key) or []
        timestamps.append(timezone.now())
        cache.set(cache_key, timestamps, timeout=86400)

    def dispatch(self, request, *args, **kwargs):
        if settings.DEBUG is True:
            bl_addr = request.GET.get('blacklist', request.META['REMOTE_ADDR'])
            dnsbl_addr = request.GET.get('dnsbl', request.META['REMOTE_ADDR'])
            rate_addr = request.GET.get('ratelimit', request.META['REMOTE_ADDR'])
        else:
            bl_addr = dnsbl_addr = rate_addr = request.META['REMOTE_ADDR']

        # Check static blacklist (settings.SPAM_BLACKLIST)
        bl_addr = ipaddress.ip_address(bl_addr)
        for network in _BLACKLIST:
            if bl_addr in network:
                log.info('%s: IP is in settings.BLACKLIST.', bl_addr)
                return TemplateResponse(request, self.blacklist_template, {})

        # Check ratelimits
        if self.check_rate(request, rate_addr) is False:
            log.info('%s: IP is ratelimited.', rate_addr)
            return TemplateResponse(request, self.rate_template, {})

        # Check DNS Blacklists
        blocks = check_dnsbl(dnsbl_addr)
        if blocks:
            log.info('%s: IP is on at least one DNSBL.', dnsbl_addr)
            return TemplateResponse(request, self.dnsbl_template, {
                'blocks': blocks,
            })

        return super(AntiSpamMixin, self).dispatch(request, *args, **kwargs)


class AnonymousRequiredMixin(object):
    """Opposite of LoginRequiredMixin.

    Some views only make sense for anonymous users - e.g. logging in, registering, ...,
    so we return the user to his details page if he is logged in.
    """

    redirect_url = reverse_lazy('account:detail')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.redirect_url)
        return super(AnonymousRequiredMixin, self).dispatch(request, *args, **kwargs)


class ContactView(AntiSpamMixin, StaticContextMixin, FormView):
    template_name = 'core/contact.html'
    rate_activity = ACTIVITY_CONTACT
    success_url = reverse_lazy('core:contact')

    def get_context_data(self, *args, **kwargs):
        context = super(ContactView, self).get_context_data(*args, **kwargs)
        context['CONTACT_MUC'] = settings.CONTACT_MUC
        return context

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return ContactForm
        else:
            return AnonymousContactForm

    def form_valid(self, form):
        config = self.request.site['NAME']
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['text']

        recipient = None
        user_pk = None

        if isinstance(form, AnonymousContactForm):
            recipient = form.cleaned_data['email']
        else:
            user_pk = self.request.user.pk

        send_contact_email.delay(config, subject, message, recipient=recipient, user_pk=user_pk,
                                 address=self.request.META['REMOTE_ADDR'])
        return self.render_to_response(self.get_context_data(form=form))


class SetLanguageView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        request = self.request

        # Some bots might attempt to use this link without the lang parameter. If not present, this
        # view basically does nothing.
        lang = request.GET.get('lang')

hp/core/templates/base.html
{% load i18n staticfiles mptt_tags canonical %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ site.BRAND }} - {% block title %}{% endblock title %}</title>

    {% if DEBUG %}
    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/prism/prism.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap-hp.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/base.css' %}" rel="stylesheet">
    {{ form.media.css }}
    {% block extracss %}{% endblock extracss %}
    {% else %}
    <link href="{% static GENERATED_CSS %}" rel="stylesheet">
    {% endif %}
    {% block pagecss %}{% endblock pagecss %}{# for CSS not included in generated CSS #}

    {% comment %}Favicons from http://www.favicomatic.com/, yeah thats insane.{% endcomment %}
    <link rel="apple-touch-icon" sizes="57x57" href="{% static "favicon/apple-touch-icon-57x57.png" %}" />
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "favicon/apple-touch-icon-114x114.png" %}" />
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "favicon/apple-touch-icon-72x72.png" %}" />
    <link rel="apple-touch-icon" sizes="144x144" href="{% static "favicon/apple-touch-icon-144x144.png" %}" />
    <link rel="apple-touch-icon" sizes="60x60" href="{% static "favicon/apple-touch-icon-60x60.png" %}" />
    <link rel="apple-touch-icon" sizes="120x120" href="{% static "favicon/apple-touch-icon-120x120.png" %}" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "favicon/apple-touch-icon-76x76.png" %}" />
    <link rel="apple-touch-icon" sizes="152x152" href="{% static "favicon/apple-touch-icon-152x152.png" %}" />
    <link rel="icon" type="image/png" href="{% static "favicon/favicon-196x196.png" sizes="196x196" %}" />
    <link rel="icon" type="image/png" href="{% static "favicon/favicon-96x96.png" sizes="96x96" %}" />
    <link rel="icon" type="image/png" href="{% static "favicon/favicon-32x32.png" sizes="32x32" %}" />
    <link rel="icon" type="image/png" href="{% static "favicon/favicon-16x16.png" sizes="16x16" %}" />
    <link rel="icon" type="image/png" href="{% static "favicon/favicon-128.png" sizes="128x128" %}" />
    <meta name="application-name" content="&nbsp;"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="{% static "favicon/mstile-144x144.png" %}" />
    <meta name="msapplication-square70x70logo" content="{% static "favicon/mstile-70x70.png" %}" />
    <meta name="msapplication-square150x150logo" content="{% static "favicon/mstile-150x150.png" %}" />
    <meta name="msapplication-wide310x150logo" content="{% static "favicon/mstile-310x150.png" %}" />
    <meta name="msapplication-square310x310logo" content="{% static "favicon/mstile-310x310.png" %}" />

    {% get_current_language as LANGUAGE_CODE %}
    <link rel="alternate" type="application/rss+xml" title="{% blocktrans with brand=request.site.BRAND %}{{ brand }} - Recent updates (RSS feed){% endblocktrans %}" href="{% canonical "feed:rss2" language=LANGUAGE_CODE %}">
    <link rel="alternate" type="application/atom+xml" title="{% blocktrans with brand=request.site.BRAND %}{{ brand }} - Recent updates (Atom feed){% endblocktrans %}" href="{% canonical "feed:atom" language=LANGUAGE_CODE %}">

    <meta name="captcha-refresh-url" content="{% url 'captcha-refresh' %}">
    <meta name="account:api-check-user" content="{% url 'account:api-check-user' %}">

    {% include "core/include/metadata.html" %}
    {% block extrahead %}{% endblock extrahead %}
  </head>
  <body>
{% block body %}
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "blog:home" %}">{{ site.BRAND }}</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% recursetree menuitems %}
            {% if node.is_leaf_node %}
            <li><a href="{{ node.target.href }}">{{ node.title.current }}</a></li>
            {% else %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ node.title.current }}<span class="caret"></span></a>
                <ul class="dropdown-menu">{{ children }}</ul>
            </li>
            {% endif %}
        {% endrecursetree %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li><a href="{% url "account:detail" %}">{% trans "Account" %}</a></li>
        <li><a href="{% url "account:logout" %}?next={{ request.path }}">{% trans "Logout" %}</a></li>
        {% else %}
        <li><a href="{% url "account:register" %}">{% trans "Register" %}</a></li>
        <li><a href="{% url "account:login" %}?next={{ request.path }}">{% trans "Login" %}</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container" role="main">
    <div class="row">{% block page %}{% endblock page %}</div>
</div>

<footer class="footer">
{% block footer %}
    <div class="container">
        <p class="text-muted">{{ COPYRIGHT_NOTICE }}</p>
<p class="text-muted">{% blocktrans %}This homepage is Free Software, you can find the source 
<a href="https://github.com/jabber-at/hp">on github</a>.{% endblocktrans %}
       </p>
    </div>
{% endblock footer %}
</footer>

{% if DEBUG %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
<script src="{% static 'lib/prism/prism.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'core/js/base.js' %}"></script>
{% block extrajs %}{% endblock extrajs %}
{{ form.media.js }}
{% else %}
<script src="{% static 'hp.js' %}"></script>
{% endif %}
{% block pagejs %}{% endblock pagejs %}
{% endblock body %}
</body></html>

hp/core/templates/error.html
{% extends "base.html" %}

{% block page %}
<div class="col-sm-9 col-md-8">
    {% block pageheader %}
    <div class="page-header"><h1>{% block title %}{{ exception.get_title }}{% endblock title %}</h1></div>
    {% endblock pageheader %}
    {% block content %}{{ exception }}{% endblock content %}
</div>
<div class="col-sm-3 col-md-4 sidebar">
    {% include "core/include/sidebar.html" %}
</div>
{% endblock page %}

hp/core/templates/page.html
{% extends "base.html" %}

{% block page %}
<div class="col-sm-9 col-md-8">
    {% block page-inner %}
    {% block pageheader %}
    <div class="page-header"><h1>{% block title %}{% endblock title %}</h1></div>
    {% endblock pageheader %}
    {% block content %}{% endblock content %}
    {% endblock page-inner %}
</div>
<div class="col-sm-3 col-md-4 sidebar">
    {% include "core/include/sidebar.html" %}
</div>
{% endblock page %}