hp/core/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.utils.translation import ugettext_lazy as _

from blog.sitemaps import BlogPostSitemap
from blog.sitemaps import PageSitemap

from . import views
from .sitemaps import StaticSitemap

sitemaps = {
    'blog': BlogPostSitemap,
    'page': PageSitemap,
    'static': StaticSitemap,
}


app_name = 'core'
urlpatterns = [
    url(_(r'^contact/$'), views.ContactView.as_view(), name='contact'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^api/set-lang/$', views.SetLanguageView.as_view(), name='api-set-lang'),
]

hp/feed/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url

from . import views

app_name = 'feed'
urlpatterns = [
    url(r'^(?P<language>[a-z][a-z])/rss.xml$', views.RSS2Feed.as_view(), name='rss2'),
    url(r'^(?P<language>[a-z][a-z])/atom.xml$', views.AtomFeed.as_view(), name='atom'),
    url(r'^(?P<language>[a-z][a-z])/ical$', views.ICalView.as_view(), name='ical'),
]

hp/hp/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

from core.urlpatterns import i18n_url

urlpatterns = [
    url(r'^%s/' % settings.ADMIN_URL.strip('/'), admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^account/', include('account.urls')),
    url(r'^feed/', include('feed.urls')),
    url(r'^chat/', include('conversejs.urls')),
    url(r'^xep0363/', include('xmpp_http_upload.urls', namespace='xmpp-http-upload')),
    i18n_url(r'^', include('core.urls')),
    url(r'^', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hp/core/forms.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from bootstrap.formfields import BootstrapCharField
from bootstrap.formfields import BootstrapChoiceField
from bootstrap.formfields import BootstrapEmailField
from bootstrap.formfields import BootstrapTextField

from .formfields import CaptchaField
from .modelfields import LinkTargetDict


class MenuItemAdminForm(forms.ModelForm):
    def clean_target(self):
        # NOTE: we don't need this in development, but in production without this the value
        #       for the target is never saved. :/
        target = LinkTargetDict(self.cleaned_data['target'])
        target.validate()
        return target


class CaptchaFormMixin(forms.Form):
    if getattr(settings, 'ENABLE_CAPTCHAS', True):
        captcha = CaptchaField(help_text=_(
            'This <a href="https://en.wikipedia.org/wiki/CAPTCHA">CAPTCHA</a> prevents '
            'automated SPAM. If you can\'t read it, just <a '
            'class="captcha-refresh">&#8634; reload</a> it.'
        ))

        class Media:
            js = (
                'core/js/captcha.js',
            )
            css = {
                'all': (
                    'core/css/captcha.css',
                ),
            }


class ContactForm(forms.Form):
    subject = BootstrapCharField(min_length=12, max_length=30, help_text=_(
        'At least 12, at most 30 characters. What is you message about?'))
    text = BootstrapTextField(min_length=100, help_text=_(
        'Please describe your issue as detailed as possible!'))


class AnonymousContactForm(CaptchaFormMixin, ContactForm):
    email = BootstrapEmailField(help_text=_('Your address, so we can get back to you.'))


class SelectOSForm(forms.Form):
    os = BootstrapChoiceField(
        label=_('Operating System'),
        label_cols=2,
        input_cols=10,
        choices=[
            ('any', _('Any operating system')),
            ('android', 'Android'),
            ('browser', 'Browser'),
            ('ios', 'iOS (iPhone)'),
            ('linux', 'Linux'),
            ('console', 'Linux (console)'),
            ('osx', 'macOS (Mac OS X)'),
            ('win', 'Windows'),
        ])

hp/core/views.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

import ipaddress
import logging

from django.conf import settings
from django.core.cache import cache
from django.db.models import Q
from django.http import Http404
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.functional import Promise
from django.utils.http import is_safe_url
from django.utils.translation import ugettext as _
from django.utils.translation import LANGUAGE_SESSION_KEY
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormView

from core.utils import canonical_link

from .constants import ACTIVITY_CONTACT
from .forms import AnonymousContactForm
from .forms import ContactForm
from .tasks import send_contact_email
from .utils import check_dnsbl

log = logging.getLogger(__name__)
_BLACKLIST = getattr(settings, 'SPAM_BLACKLIST', set())
_RATELIMIT_WHITELIST = getattr(settings, 'RATELIMIT_WHITELIST', set())
_RATELIMIT_CONFIG = getattr(settings, 'RATELIMIT_CONFIG', {})


class TranslateSlugViewMixin(object):
    """A view mixin that allows DetailView to work with translated slugs.

    .. WARNING:: This mixin assumes:

       * There is a ``slug`` kwarg in the URL config
       * The model has a translated slug field (like core.BlogPost and core.Page)
       * The model has a ``get_absolute_url()`` method.

    Background: By default, get_object() would filter for the slug field, the translated
    database field uses the current active language. So this queryset::

        >>> from blog.models import Page
        >>> Page.objects.filter(slug='foo')

    ... returns a different result depending on the browser language (on the database level,
    this would result in a ``WHERE slug_en="foo"`` in an English browser). This means that
    the URL "/page/english-slug" works in an English browser but NOT in a German browser.

    So ``get_object()`` is overwritten to filter for all language slugs. ``get()`` additionally
    returns a redirect to the slug in the current language if it's not the same as the one viewed.
    """

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        # If the slug used in the view is different from the slug in the current language, redirect
        # to the latter.
        if kwargs['slug'] != self.object.slug.current:
            return HttpResponseRedirect(self.object.get_absolute_url())

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        slug = self.kwargs.get(self.slug_url_kwarg)

        # filter for slugs in all languages
        filter = Q()
        for lang, _name in settings.LANGUAGES:
            filter |= Q(**{'slug_%s' % lang: slug})

        queryset = queryset.filter(filter)

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj


class StaticContextMixin(object):
    """Simple mixin that allows you to add a static dictionary to the template context."""

    static_context = None

    def get_context_data(self, **kwargs):
        context = super(StaticContextMixin, self).get_context_data(**kwargs)
        if self.static_context is not None:
            context.update(self.static_context)

        urlname = '%s:%s' % (self.request.resolver_match.namespace,
                             self.request.resolver_match.url_name)

        if urlname in settings.SOCIAL_MEDIA_TEXTS:
            texts = settings.SOCIAL_MEDIA_TEXTS[urlname]

            for key, value in texts.items():
                if isinstance(value, (str, Promise)):
                    value = value % self.request.site
                context[key] = value

        # set default canonical URL
        context.setdefault('canonical_url', canonical_link(self.request.path))

        return context


class AntiSpamMixin(object):
    blacklist_template = 'core/antispam/blacklist.html'
    dnsbl_template = 'core/antispam/dnsbl.html'
    rate_template = 'core/antispam/rate.html'
    rate_activity = None

    def get_rate_cache_key(self, request):
        return 'rate_%s_%s' % (self.rate_activity, request.META['REMOTE_ADDR'])

    def check_rate(self, request, rate_addr):
        """Check if the given IP is currently ratelimited for this view.

        Returns
        -------

        bool
            Returns ``False`` if the IP is currently ratelimited for this activity, ``True``
            otherwise.
        """

        if self.rate_activity is None:
            return True
        if rate_addr in _RATELIMIT_WHITELIST or settings.DEBUG is True:
            return True

        cache_key = self.get_rate_cache_key(request)
        now = timezone.now()
        timestamps = cache.get(cache_key) or []
        config = _RATELIMIT_CONFIG.get(self.rate_activity, {})

        for delta, ratelimit in config:
            offset = now - delta
            if len([t for t in timestamps if t >= offset]) > ratelimit:
                return False
        return True

    def ratelimit(self, request):
        if settings.DEBUG is True:
            rate_addr = request.GET.get('ratelimit', request.META['REMOTE_ADDR'])
        else:
            rate_addr = request.META['REMOTE_ADDR']

        if rate_addr in _RATELIMIT_WHITELIST or self.rate_activity is None:
            return

        cache_key = self.get_rate_cache_key(request)
        timestamps = cache.get(cache_key) or []
        timestamps.append(timezone.now())
        cache.set(cache_key, timestamps, timeout=86400)

    def dispatch(self, request, *args, **kwargs):
        if settings.DEBUG is True:
            bl_addr = request.GET.get('blacklist', request.META['REMOTE_ADDR'])
            dnsbl_addr = request.GET.get('dnsbl', request.META['REMOTE_ADDR'])
            rate_addr = request.GET.get('ratelimit', request.META['REMOTE_ADDR'])
        else:
            bl_addr = dnsbl_addr = rate_addr = request.META['REMOTE_ADDR']

        # Check static blacklist (settings.SPAM_BLACKLIST)
        bl_addr = ipaddress.ip_address(bl_addr)
        for network in _BLACKLIST:
            if bl_addr in network:
                log.info('%s: IP is in settings.BLACKLIST.', bl_addr)
                return TemplateResponse(request, self.blacklist_template, {})

        # Check ratelimits
        if self.check_rate(request, rate_addr) is False:
            log.info('%s: IP is ratelimited.', rate_addr)
            return TemplateResponse(request, self.rate_template, {})

        # Check DNS Blacklists
        blocks = check_dnsbl(dnsbl_addr)
        if blocks:
            log.info('%s: IP is on at least one DNSBL.', dnsbl_addr)
            return TemplateResponse(request, self.dnsbl_template, {
                'blocks': blocks,
            })

        return super(AntiSpamMixin, self).dispatch(request, *args, **kwargs)


class AnonymousRequiredMixin(object):
    """Opposite of LoginRequiredMixin.

    Some views only make sense for anonymous users - e.g. logging in, registering, ...,
    so we return the user to his details page if he is logged in.
    """

    redirect_url = reverse_lazy('account:detail')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.redirect_url)
        return super(AnonymousRequiredMixin, self).dispatch(request, *args, **kwargs)


class ContactView(AntiSpamMixin, StaticContextMixin, FormView):
    template_name = 'core/contact.html'
    rate_activity = ACTIVITY_CONTACT
    success_url = reverse_lazy('core:contact')

    def get_context_data(self, *args, **kwargs):
        context = super(ContactView, self).get_context_data(*args, **kwargs)
        context['CONTACT_MUC'] = settings.CONTACT_MUC
        return context

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return ContactForm
        else:
            return AnonymousContactForm

    def form_valid(self, form):
        config = self.request.site['NAME']
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['text']

        recipient = None
        user_pk = None

        if isinstance(form, AnonymousContactForm):
            recipient = form.cleaned_data['email']
        else:
            user_pk = self.request.user.pk

        send_contact_email.delay(config, subject, message, recipient=recipient, user_pk=user_pk,
                                 address=self.request.META['REMOTE_ADDR'])
        return self.render_to_response(self.get_context_data(form=form))


class SetLanguageView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        request = self.request

        # Some bots might attempt to use this link without the lang parameter. If not present, this
        # view basically does nothing.
        lang = request.GET.get('lang')

hp/core/templates/core/include/facebook_link.html
<div class="smfb-btn facebook-link-btn"><div>
    <a href="https://facebook.com/{{ facebook }}">
        <span class="fb-logo">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" class="svg-logo"><path fill="#ffffff" fill-rule="evenodd" d="M8 14H3.667C2.733 13.9 2 13.167 2 12.233V3.667A1.65 1.65 0 0 1
                3.667 2h8.666A1.65 1.65 0 0 1 14 3.667v8.566c0 .934-.733
                1.667-1.667
                1.767H10v-3.967h1.3l.7-2.066h-2V6.933c0-.466.167-.9.867-.9H12v-1.8c.033
                0-.933-.266-1.533-.266-1.267 0-2.434.7-2.467
                2.133v1.867H6v2.066h2V14z"></path></svg>
        </span>

        <span class="fb-label">/{{ facebook }}</span>
    </a>
</div></div>

hp/core/templates/core/include/messages.html
<div class="messages">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}<strong>Error:</strong>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}<strong>Warning:</strong>
        {% endif %} 
        {{ message }}</div>
    {% endfor %}
{% endif %}
</div>

hp/core/templates/core/include/metadata.html
{% load canonical %}
{% comment %}Metatags{% endcomment %}
{% if meta_desc %}<meta name="description" content="{{ meta_desc }}">{% endif %}
{% if canonical_url %}<link rel="canonical" href="{{ canonical_url }}" />{% endif %}

{% comment %}TWITTER{% endcomment %}
{% if TWITTER_HANDLE %}<meta name="twitter:site" content="@{{ TWITTER_HANDLE }}" />{% endif %}
<meta name="twitter:card" content="summary" />
<meta name="twitter:image" content="{% canonical_static "core/img/twitter.png" %}" />
{% if twitter_title %}<meta name="twitter:title" content="{{ twitter_title }}" />
{% elif title %}<meta name="twitter:title" content="{{ title }}" />
{% endif %}
{% if twitter_desc|default:meta_desc %}<meta name="twitter:description" content="{{ twitter_desc|default:meta_desc }}" />{% endif %}

{% comment %}FACEBOOK{% endcomment %}

<meta property="og:type" content="{{ og_type|default:"website" }}" />
<meta property="og:site_name" content="{{ default_site.BRAND }}" />
<meta property="og:image" content="{% canonical_static "core/img/fb.png" %}" />
<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" />
{% if og_type == "article" %}
    {% if FACEBOOK_PAGE %}
        <meta property="article:author" content="https://facebook.com/{{ FACEBOOK_PAGE }}" />
        <meta property="article:publisher" content="https://facebook.com/{{ FACEBOOK_PAGE }}" />
    {% endif %}
{% if updated %}<meta property="article:modified_time" content="{{ updated|date:"c" }}" />{% endif %}
{% if created %}<meta property="article:published_time" content="{{ created|date:"c" }}" />{% endif %}
{% endif %}

{% if FACEBOOK_PAGE %}
<meta property="fb:pages" content="{{ FACEBOOK_PAGE }}" />
{% endif %}

{% if updated %}<meta property="og:updated_time" content="{{ updated|date:"c" }}" />{% endif %}
{% if canonical_url %}<meta property="og:url" content="{{ canonical_url }}" />{% endif %}
{% if og_title %}<meta property="og:title" content="{{ og_title }}" />
{% elif title %}<meta name="twitter:title" content="{{ title }}" />
{% endif %}
{% if og_desc|default:meta_desc %}<meta property="og:description" content="{{ og_desc|default:meta_desc }}" /> {% endif %}
{% comment %}TODO: image, locales {% endcomment %}

hp/core/templates/core/include/sidebar.html
{% load i18n static canonical %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">{% trans "Language" %}</h3>
  </div>
  <ul class="list-group">
  {% for code, name in other_langs %}
    {% language code %}
    <li class="list-group-item">
        <a href="{% url "core:api-set-lang" %}?lang={{ code }}&next={{ request.get_full_path|urlencode }}" rel="nofollow">
            <img src="{% static "core/img/" %}{{ code }}.svg" class="bullet" 
               alt="{% blocktrans with lang=name %}Switch to {{ lang }}{% endblocktrans %}" />{{ name }}
        </a>
    </li>
    {% endlanguage %}
  {% endfor %}
  </ul>
</div>

<div class="panel panel-default follow-panel">
  <div class="panel-heading">
    <h3 class="panel-title">{% trans "Updates" %}</h3>
  </div>
  <div class="panel-body"><p>{% trans "If you use our server, we strongly encourage you to stay up to date." %}</p></div>
  <ul class="list-group" itemscope itemtype="http://schema.org/Organization">
    <link itemprop="url" href="{% canonical "blog:home" %}">
    {% if TWITTER_HANDLE %}
    <li class="list-group-item">
        <a href="https://twitter.com/{{ TWITTER_HANDLE }}" itemprop="sameAs">
            <img src="{% static "core/img/smtw.svg" %}" class="bullet"
                alt="{% blocktrans with brand=site.BRAND %}{{ brand }} on Twitter{% endblocktrans %}">
                    @{{ TWITTER_HANDLE }}
        </a>
    </li>
    {% endif %}
    {% if FACEBOOK_PAGE %}
    <li class="list-group-item">
        <a href="https://facebook.com/{{ FACEBOOK_PAGE }}" itemprop="sameAs">
            <img src="{% static "core/img/629hwmjt.svg" %}" class="bullet"
                alt="{% blocktrans with brand=site.BRAND %}{{ brand }} on Facebook{% endblocktrans %}">
            /{{ FACEBOOK_PAGE }}</a>
    </li>
    {% endif %}
    <li class="list-group-item">
        <a href="{% url "feed:rss2" language=LANGUAGE_CODE %}">
            <img src="{% static "core/img/rss.svg" %}" class="bullet"
                alt="{% blocktrans with brand=site.BRAND %}RSS feed for {{ brand }}{% endblocktrans %}">
            RSS feed
        </a>
    </li>
    <li class="list-group-item">
        <a href="{% url "feed:atom" language=LANGUAGE_CODE %}">
            <img src="{% static "core/img/rss.svg" %}" class="bullet"
                alt="{% blocktrans with brand=site.BRAND %}Atom feed for {{ brand }}{% endblocktrans %}">
            Atom feed</a>
    </li>
  </ul>
</div>

hp/core/templates/core/include/twitter_follow.html
{% load i18n %}
<div class="smtw-btn smtw-follow-btn">
    <a class="smtw-follow" href="https://twitter.com/intent/follow?screen_name={{ twitter }}">
<i></i><span class="label">{% blocktrans with handle=twitter %}Follow <strong>@{{ twitter }}</strong>{% endblocktrans %}</span></a>
</div>

hp/core/templates/core/include/twitter_link.html
{% load i18n %}
<div class="smtw-btn smtw-link-btn">
    <a class="smtw-follow" href="https://twitter.com/{{ twitter }}">
        <i></i>
        <span class="label">{% blocktrans with twitter=twitter %}@{{ twitter }}{% endblocktrans %}</span>
    </a>
</div>